Repository FluidSimP/rafa-simp, pull requests merged in 2022-10, with the labels that each got.

#2 fof
  Exercise 1/exercise1.ct
Labels: hacktoberfest-accepted

#3 Update readme
  README.md
Labels: enhancement, hacktoberfest-accepted

#4 Added base files for the second exercise
  Exercise 2/README.md
  Exercise 2/exercise2.ct
Labels: documentation, hacktoberfest-accepted

#5 exercise update
  Exercise 2/README.md
  Exercise 2/exercise2.ct
Labels: documentation, enhancement, hacktoberfest-accepted

#6 Added base files for the third exercise
  Exercise 3/README.md
  Exercise 3/exercise3.ct
Labels: documentation, hacktoberfest-accepted

#7 l don't think at this time of the day
  Exercise 3/README.md
  Exercise 3/exercise3.ct
Labels: hacktoberfest-accepted
